In [25]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
import os
current_path = os.getcwd()
current_path

'C:\\Users\\Shivank garg'

In [4]:
dataframe= pd.read_csv("train.csv", header=None)
dftest= pd.read_csv("test.csv", header=None)


C:\Users\Shivank garg\AppData\Local\Temp\ipykernel_21612\161675896.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,25

In [5]:
dataframe.head()

0                     1                    2                    3     \
0  labels                   f_0                  f_1                  f_2   
1       0   -2.0338754847514076   0.9784459341144622  -0.1421308401166783   
2       1  -0.34883507271702585  0.29481456283081336  -0.5575766736236175   
3       1     0.113247803879688   -0.607725685220181  -0.9477910279408399   
4       0    1.2233209192853869  -0.4790480627697671  -1.9257889089567417   

                   4                     5                    6     \
0                   f_3                   f_4                  f_5   
1  -0.17711703501154927   -1.4706840047636902   1.6695623289421941   
2   -2.0207727956959505   -1.2347153930615196   1.6339301260293642   
3    0.8308509405069512    0.9982909738046802  0.49832088627350685   
4     1.680376707475607  0.021840467070529515  -1.4533069034209085   

                   7                      8                    9     ...  \
0                   f_6                    f_7                  f_8  ...   
1  -0.19652975909853684    -0.1252386301384724  -0.4522844255730295  ...   
2   -1.6806584041297072    -0.3581457219894779  0.16612181759450426  ...   
3    -1.493958360949691     0.7895718864951502  -1.3110180776845535  ...   
4    0.6055593380187781  -0.019024011988712706    1.065447664850538  ...   

                  1191                1192                  1193  \
0               f_1190              f_1191                f_1192   
1  -1.1112658145100465  0.7160835790790151  0.060039060398674786   
2    0.735240428445085   0.829781288146005     1.521941355809489   
3   0.1046981689668915  0.6161892846239375   -1.0359528971009342   
4   0.3602369794340369  -1.957863263193831  -0.12338374704090385   

                 1194                 1195                 1196  \
0              f_1193               f_1194               f_1195   
1   0.301279104628461  -1.1748459564577958   -1.076498490875714   
2  1.3479456224981563   0.7545052782333206   1.3306420619963777   
3   2.111387146820228   -0.984414620904498   1.1480756131093413   
4  1.5053289508509657   0.6602904672299815  -1.7694428174974057   

                   1197                 1198                 1199  \
0                f_1196               f_1197               f_1198   
1  -0.06945243165009196  -0.6040120219413277   -2.179175631864767   
2    -0.754453180396377   0.5829564533383925   0.2526709780911331   
3    -1.433554203291222   0.2433724502194554  0.17008343495959583   
4    -0.547756262665183   -0.568121575372889  0.24464460762158835   

                 1200  
0              f_1199  
1  0.5580031551308428  
2  1.4958698108055448  
3   1.274795045377175  
4  0.9821155381726155  

[5 rows x 1201 columns]

In [48]:
Xtrain = dataframe.iloc[1:, 1:1201].astype(float)
Ytrain = dataframe.iloc[1:, 0].astype(float)
Xtest = dftest.iloc[1:, 1:1201].astype(float)



In [7]:
Xtrain

1         2         3         4         5         6         7     \
1    -2.033875  0.978446 -0.142131 -0.177117 -1.470684  1.669562 -0.196530   
2    -0.348835  0.294815 -0.557577 -2.020773 -1.234715  1.633930 -1.680658   
3     0.113248 -0.607726 -0.947791  0.830851  0.998291  0.498321 -1.493958   
4     1.223321 -0.479048 -1.925789  1.680377  0.021840 -1.453307  0.605559   
5     0.160109  0.422684 -0.308029  0.227744  0.432854  0.608348  0.193832   
...        ...       ...       ...       ...       ...       ...       ...   
5246  1.157565 -0.142219  1.043992  1.144946  1.195423  0.248978 -1.505100   
5247  1.424709  0.235910  1.356778  1.368099 -0.318862  1.039765 -0.986854   
5248 -0.375687  1.524455  0.012514 -0.007917  0.073809 -0.906909 -1.254247   
5249 -0.478238  1.666142  0.049609 -0.428752 -0.362771  1.798104 -0.214314   
5250 -0.750874  0.267008 -0.155041 -0.179867 -0.155041 -0.303999 -0.279173   

          8         9         10    ...      1191      1192      1193  \
1    -0.125239 -0.452284 -0.128052  ... -1.111266  0.716084  0.060039   
2    -0.358146  0.166122 -1.656990  ...  0.735240  0.829781  1.521941   
3     0.789572 -1.311018  0.848524  ...  0.104698  0.616189 -1.035953   
4    -0.019024  1.065448  0.717341  ...  0.360237 -1.957863 -0.123384   
5     1.035091 -0.538868  0.778445  ...  0.416629  1.441766  0.212572   
...        ...       ...       ...  ...       ...       ...       ...   
5246 -0.874137 -1.782724  0.261597  ...  1.195423 -0.255793 -0.154838   
5247 -0.330184 -1.383120  1.243559  ...  1.424709 -1.066107  0.881258   
5248  1.606182  0.298557  0.053378  ... -0.028349 -0.968204 -1.233815   
5249  0.775400 -0.379267  0.725914  ... -0.428752 -1.121552 -0.379267   
5250  1.731765  0.564925  1.508328  ... -0.303999 -0.850180  0.937321   

          1194      1195      1196      1197      1198      1199      1200  
1     0.301279 -1.174846 -1.076498 -0.069452 -0.604012 -2.179176  0.558003  
2     1.347946  0.754505  1.330642 -0.754453  0.582956  0.252671  1.495870  
3     2.111387 -0.984415  1.148076 -1.433554  0.243372  0.170083  1.274795  
4     1.505329  0.660290 -1.769443 -0.547756 -0.568122  0.244645  0.982116  
5    -0.994721  1.143999 -2.166923 -1.199248 -1.028636  0.752791  0.317169  
...        ...       ...       ...       ...       ...       ...       ...  
5246  0.413029 -0.482939 -1.277953 -0.445082  1.195423 -0.924614 -0.432462  
5247 -0.488691 -1.281223 -1.213291  0.122692  1.175627 -1.145360  0.451026  
5248  1.626613 -0.191802  1.115823  0.380284 -0.293960  0.135104  1.381434  
5249 -0.593705  0.049609  1.765114  0.313533 -0.329781 -1.220524  0.033114  
5250 -1.594972  1.036626  1.582807  1.036626 -0.254346  0.664230  1.831071  

[5250 rows x 1200 columns]

In [8]:
Ytrain

1       0
2       1
3       1
4       0
5       0
       ..
5246    0
5247    0
5248    1
5249    1
5250    1
Name: 0, Length: 5250, dtype: object

In [9]:
model = Sequential()
model.add(Dense(256, input_dim=1200, activation='relu')) 
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])



In [10]:

model.summary()     


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               307456    
                                                                 
 dense_1 (Dense)             (None, 128)               32896     
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 32)                2080      
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 350,721
Trainable params: 350,721
Non-trainable params: 0
_________________________________________________________________


In [17]:

 from sklearn.model_selection import train_test_split
 X_train, X_val, Y_train, Y_val = train_test_split(Xtrain,Ytrain, test_size=0.2)    

In [18]:
history = model.fit(X_train,Y_train,epochs=25,validation_data=(X_val,Y_val))

Epoch 1/25
132/132 [==============================] - 3s 15ms/step - loss: 0.3369 - accuracy: 0.8400 - val_loss: 0.3235 - val_accuracy: 0.8476
Epoch 2/25
132/132 [==============================] - 2s 14ms/step - loss: 0.0970 - accuracy: 0.9652 - val_loss: 0.4985 - val_accuracy: 0.8219
Epoch 3/25
132/132 [==============================] - 1s 11ms/step - loss: 0.0308 - accuracy: 0.9926 - val_loss: 0.6878 - val_accuracy: 0.8457
Epoch 4/25
132/132 [==============================] - 1s 11ms/step - loss: 0.0179 - accuracy: 0.9940 - val_loss: 0.7354 - val_accuracy: 0.8448
Epoch 5/25
132/132 [==============================] - 2s 13ms/step - loss: 0.0089 - accuracy: 0.9976 - val_loss: 0.9313 - val_accuracy: 0.8438
Epoch 6/25
132/132 [==============================] - 2s 13ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 1.0489 - val_accuracy: 0.8362
Epoch 7/25
132/132 [==============================] - 2s 12ms/step - loss: 1.3937e-04 - accuracy: 1.0000 - val_loss: 1.1010 - val_accuracy: 0.

In [19]:
scaler=StandardScaler()
scaler.fit_transform(X_train)

array([[-1.76825371, -0.7297375 , -0.74909348, ..., -0.34849333,
         0.00731146, -0.03518256],
       [-1.82920217, -0.91172681, -0.98808716, ...,  0.42681018,
        -1.18005351, -2.48695353],
       [-0.38117992,  0.52992605, -2.23842543, ..., -0.07934091,
         0.53751999,  1.14071072],
       ...,
       [ 0.95189498, -0.4362282 ,  0.8394476 , ...,  0.93333885,
        -0.67172727, -0.35164509],
       [-1.14084966,  0.63102523,  0.39776863, ...,  0.27830513,
         1.93750669, -0.78038545],
       [ 0.78509044, -0.52310864,  0.81127777, ...,  0.76926298,
        -0.62738451, -0.49095059]])

In [34]:

Y_pred=model.predict(Xtest)     


71/71 [==============================] - 0s 5ms/step


In [53]:
Y_pred


array([[9.9999928e-01],
       [2.9640076e-01],
       [6.5919794e-03],
       ...,
       [1.0000000e+00],
       [1.5473318e-28],
       [9.9999994e-01]], dtype=float32)

In [36]:
def roundoff(x):
  if x>0.5:
    return 1
  else:
    return 0

In [50]:
Y_predround=np.array([roundoff(x) for x in Y_pred])

In [54]:
Y_predround

array([1, 0, 0, ..., 1, 0, 1])

In [56]:
DF = pd.DataFrame(Y_predround)

In [57]:
DF.to_csv("submission.csv")
